### ISSUE TITLE
Please update dpkg recipe to a supported version

### ISSUE THREAD

**Issue by guillemj** [gobolinux/Recipes#1]
Hi!

I'm upstream for dpkg, and I try to check downstream support from time to time (tracked at https://wiki.debian.org/Teams/Dpkg/Downstream). Currently GoboLinux is one of the few that packages an unsupported dpkg version series. It would be nice if you could update to either 1.17.x (current stable series) or 1.18.x (current development series) depending on your version inclusion policies. I'll gladly help and consider adding support for changes that might make your packaging possible or easier!

Thanks,
Guillem

**Comment by shevegen** [comment]
Adding some links to the issue request:

http://ftp.debian.org/debian/pool/main/d/dpkg/?C=M;O=D

http://mirrors.kernel.org/debian/pool/main/d/dpkg/dpkg_1.18.4.tar.xz

**Comment by lucasvr** [comment]
Recipe updated:
https://github.com/gobolinux/Recipes/commit/145ba2dbffaa14f611be93f06c7100a09e7819a8
