### ISSUE TITLE
Htop 3.0.4 does not show any processes after installing

### ISSUE THREAD

**Issue by Nuc1eoN** [gobolinux/Recipes#111]
Htop 2.2.0 works fine here, but Htop 3.0.4's process list is empty on my end.

**Comment by Nuc1eoN** [comment]
@hishamhm Maybe you could take a look :)

**Comment by hishamhm** [comment]
I can't reproduce it on my end... do you have multiple versions of ncurses (and/or ncursesw) installed? it may be linking to the wrong one, or there may be a mismatch between headers during compilation and libraries in use.

**Comment by Nuc1eoN** [comment]
Hi thanks for helping. I have only NcursesW installed, in version `6.2`.

Indeed it seems NcursesW related though. I have attached the [config.log](https://github.com/gobolinux/Recipes/files/5976819/config.log) which contains:
```
configure:6231: result: no
configure:6231: checking ncurses/curses.h presence
configure:6231: gcc -E  conftest.c
conftest.c:49:10: fatal error: ncurses/curses.h: No such file or directory
   49 | #include <ncurses/curses.h>
      |          ^~~~~~~~~~~~~~~~~~
```
When Running `strace htop`, the first lines show:
```
execve("/usr/bin/htop", ["htop"], [/* 76 vars */]) = 0
brk(0)                                  = 0x215c000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/Programs/NcursesW/6.2/lib/tls/x86_64/x86_64/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Programs/NcursesW/6.2/lib/tls/x86_64/x86_64", 0x7ffea5d469b0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/Programs/NcursesW/6.2/lib/tls/x86_64/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Programs/NcursesW/6.2/lib/tls/x86_64", 0x7ffea5d469b0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/Programs/NcursesW/6.2/lib/tls/x86_64/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Programs/NcursesW/6.2/lib/tls/x86_64", 0x7ffea5d469b0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/Programs/NcursesW/6.2/lib/tls/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Programs/NcursesW/6.2/lib/tls", 0x7ffea5d469b0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/Programs/NcursesW/6.2/lib/x86_64/x86_64/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Programs/NcursesW/6.2/lib/x86_64/x86_64", 0x7ffea5d469b0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/Programs/NcursesW/6.2/lib/x86_64/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Programs/NcursesW/6.2/lib/x86_64", 0x7ffea5d469b0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/Programs/NcursesW/6.2/lib/x86_64/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/Programs/NcursesW/6.2/lib/x86_64", 0x7ffea5d469b0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/Programs/NcursesW/6.2/lib/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = 3
```

**Comment by Nuc1eoN** [comment]
#113 miiiight be related. However I have manually fixed `htop`s Dependencies file (which normally resolves any resulting issues for me), but it did not fix the issue presented in this ticket.

**Comment by hishamhm** [comment]
Do you have multiple versions of ncursesw around? It might have compiled with the .h files from a different version. I have 6.0 only.

**Comment by Nuc1eoN** [comment]
No, I only one version of `NcursesW`:
```
ls /Programs/NcursesW 
6.2  Current  Settings
```
And I don't have `Ncurses` (without the "W") installed.

**Comment by hishamhm** [comment]
I have seen this kind of problem in the distant past, but it was usually ncurses miscompilation... I don't have many ideas now. Did you try it on a different terminal?

**Comment by Nuc1eoN** [comment]
Sorry I thought I had answered already.

Yes I've tried it on urxwt and xterm, but same thing occurs.

Is there anything else I can try?

**Comment by hishamhm** [comment]
Unfortunately I'm out of ideas... Did you try htop 3.0.3? If that works,
you may want to report a regression to the current htop maintainers, maybe?

**Comment by Nuc1eoN** [comment]
@hishamhm That was a good idea :)
The regression apparently came with htop 3.0.3, while everything still works as it should on htop 3.02.
I am gonna report it to th htop maintainers then (sorry I thought you were still a maintainer :smile: )

**Comment by lucasvr** [comment]
@Nuc1eoN the new recipe has been just merged. Are we good to close this one now?

**Comment by Nuc1eoN** [comment]
@lucasvr Hey sure, it's an upstream issue now I guess. Closed.
