### ISSUE TITLE
Truncated repository list on GitHub

### ISSUE THREAD

**Issue by mdziczkowski** [gobolinux/Recipes#129]
Could the project developers and/or owner check if all folders and file's are in tact, because I recieved a following error:

>  Sorry, we had to truncate this directory to 1,000 files. 2,718 entries were omitted from the list.

**Comment by Nuc1eoN** [comment]
>Sorry, we had to truncate this directory to 1,000 files. 2,718 entries were omitted from the list.

That is a limitation to GitHub and not anything specific to GoboLinux.

**Comment by mdziczkowski** [comment]
thanks for checking it. If GitHub does such things then wouldn't it beter to put the repo in another place, where it wouldn't become truncated? Else, users will have hard to check, if there is avaliable in the repo an program of their interest

**Comment by waldyrious** [comment]
> Else, users will have hard to check, if there is avaliable in the repo an program of their interest

FYI, you can still use the search, or even better, the `t` shortcut to open the interactive file finder.

I, for one, wouldn't want a repository with thousands of entries at the root level to produce an extremely long page that one would need to scroll a lot to navigate. A limit of 1000 _for display alone_ sounds reasonable to me (although I can agree the warning is worded somewhat awkwardly, and styled in a way that makes it seem more problematic than it really is).

**Comment by mdziczkowski** [comment]
> I, for one, wouldn't want a repository with thousands of entries at the root level to produce an extremely long page that one would need to scroll a lot to navigate. A limit of 1000 _for display alone_ sounds reasonable to me (although I can agree the warning is worded somewhat awkwardly, and styled in a way that makes it seem more problematic than it really is).

It would be easier to use paging while browsing then this akward message and no possibility to see more ;-)

**Comment by Nuc1eoN** [comment]
As @waldyrious said you can use the file search to find programs.

Also the repository resides on your hard disk under `/Data/Compile/Recipes` which you can easily query.

So I don't think we have an issue here?

**Comment by mdziczkowski** [comment]
> So I don't think we have an issue here?

I didn't meant it as an issue... more as request if GitHub hasn't damaged the repository placed on GitHub thru truncating it

**Comment by Nuc1eoN** [comment]
Yes luckily the repository itself is fine :)

Also be sure to check out the forums, in case you have more general requests https://gobolinux.discourse.group/. The devs are around there.

**Comment by mdziczkowski** [comment]
Good to know about it ;-) I think that (for any case) would be a good idea to have a backup locations with the files and repos, in case that GitHub suddenly changes it's mind ;-)

**Comment by Nuc1eoN** [comment]
As mentioned before, a whole copy of all the recipes hosted here are also available in everyone's `/Data/Compile/Recipes` directory. So every GoboLinux user basically has a backup.
