### ISSUE TITLE
Why the openssldir parameter changed?

### ISSUE THREAD

**Issue by mikrosk** [gobolinux/Recipes#13]
OpenSSL 1.0.2e: --openssldir="/usr/lib/ssl"

OpenSSL 1.0.2j: --openssldir=/etc/ssl

I'm asking mainly because CA-Certificates still install into ":lib/ssl/certs" so this change doesn't seem right to me (I'm trying to harvest your scripts for my own usage ;-))

**Comment by AitorATuin** [comment]
@mikrosk Certificates are now installed under /etc, that was the reason for the change.
