### ISSUE TITLE
Unable to `Compile unionfs`

### ISSUE THREAD

**Issue by BoQsc** [gobolinux/Recipes#137]
## Update
The link `https://gobolinux.org/mirror_url/Unionfs/1.0.14/unionfs-1.0.14.tar.gz` is dead and downloads 0 byte file.
The link `ftp.fsl.cs.sunysb.edu/pub/unionfs/unionfs-1.0.14.tar.gz`  is dead and downloads 0 byte file.

It seems that it tries to download a `unionfs-1.0.14.tar.gz` file from `ftp.fsl.cs.sunysb.edu/pub/unionfs/unionfs-1.0.14.tar.gz`, it connects to the page, but the page has been marked as deleted on the server and therefore downloads empty file named `unionfs-1.0.14.tar.gz`
![image](https://user-images.githubusercontent.com/21064622/127778638-d1fae2bf-8d4f-467f-bf76-9ec92de18bf6.png)

Same happens for both links.

## Pull Request Information
**Source to look up and do corrections on:**  
https://github.com/gobolinux/Recipes/blob/master/Unionfs/1.0.14/Recipe

**A new replacement source here:**  
http://distrib-coffee.ipsl.jussieu.fr/pub/linux/devil-linux/devel/sources/1.2/unionfs-1.0.14.tar.gz

**As a Mirror for this file, I upload here on GitHub:**  
[unionfs-1.0.14.tar.gz](https://github.com/gobolinux/Recipes/files/6913002/unionfs-1.0.14.tar.gz)

## OLD
While on Live CD I tried to Compile unionfs and this is what happened.
```
root@LiveCD ~]Compile unionfs
Compile: Initializing recipes repository
Cloning into '/Data/Compile/Recipes'...
remote: Enumerating objects: 205396, done.
remote: Counting objects: 100% (402/402), done.
remote: Compressing objects: 100% (311/311), done.
remote: Total 205396 (delta 124), reused 294 (delta 68), pack-reused 204994
Receiving objects: 100% (205396/205396), 43.81 MiB | 1.05 MiB/s, done.
Resolving deltas: 100% (58331/58331), done.
Updating files: 100% (58035/58035), done.
Already up to date.
Compile: Checking dependencies...
Compile: Compiling Unionfs version 1.0.14.
Compile: Running without dependency-based namespace (Runner not available).
--2021-08-01 15:12:11--  ftp://ftp.fsl.cs.sunysb.edu/pub/unionfs/unionfs-1.0.14.tar.gz
           => 'unionfs-1.0.14.tar.gz'
Resolving ftp.fsl.cs.sunysb.edu (ftp.fsl.cs.sunysb.edu)... 130.245.126.1
Connecting to ftp.fsl.cs.sunysb.edu (ftp.fsl.cs.sunysb.edu)|130.245.126.1|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/unionfs ... done.
==> SIZE unionfs-1.0.14.tar.gz ... done.

==> PASV ... done.    ==> RETR unionfs-1.0.14.tar.gz ... 
No such file 'unionfs-1.0.14.tar.gz'.

--2021-08-01 15:12:16--  https://gobolinux.org/mirror_url/Unionfs/1.0.14/unionfs-1.0.14.tar.gz
Resolving gobolinux.org (gobolinux.org)... 69.163.217.231
Connecting to gobolinux.org (gobolinux.org)|69.163.217.231|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0 [application/gzip]
Saving to: 'unionfs-1.0.14.tar.gz'

unionfs-1.0.14.tar.     [ <=>              ]       0  --.-KB/s    in 0s      

2021-08-01 15:12:17 (0.00 B/s) - 'unionfs-1.0.14.tar.gz' saved [0/0]

FetchArchive: Warning: /Data/Compile/Archives/unionfs-1.0.14.tar.gz is either not complete or corrupted.
FetchArchive: File /Data/Compile/Archives/unionfs-1.0.14.tar.gz is incomplete or can not be verified
Compile: Error fetching archive(s).
Compile: Unionfs 1.0.14 - Fetching sources failed
root@LiveCD ~]
```

**Comment by lucasvr** [comment]
This is an old package that no longer has a corresponding kernel component -- so the userspace tool becomes a bit useless. Please resort to overlayfs or unionfs-fuse instead. Thanks.
