### ISSUE TITLE
Please update vulnerable uriparser 0.9.5 to 0.9.6

### ISSUE THREAD

**Issue by hartwork** [gobolinux/Recipes#149]
Hi!

I found a vulnerable copies of uriparser 0.7.5/0.8.6/0.9.5 in here at [`LibURIParser`](https://github.com/gobolinux/Recipes/tree/master/LibURIParser). uriparser 0.9.6 with security fixes has been released, the [change log](https://github.com/uriparser/uriparser/blob/uriparser-0.9.6/ChangeLog) has more details. Would be awesome if you could update to 0.9.6.  Thank you! :pray:

Best, Sebastian

**Comment by Nuc1eoN** [comment]
Awesome, updated in commit https://github.com/gobolinux/Recipes/commit/aa058689fcf9455cda8a8c0122712ff6dd4fe346! ￼:pray:

**Comment by hartwork** [comment]
@Nuc1eoN thank you!
