### ISSUE TITLE
Linux: Recipes are horrendously out of date

### ISSUE THREAD

**Issue by ghost** [gobolinux/Recipes#183]
The latest version of the Linux kernel upstream is Linux 6.0. The latest recipe in the tree is 5.9.8! the latest in the tree is not even supported anymore. Updating is needed.

**Comment by barkabar999** [comment]
@lucasvr

**Comment by Nuc1eoN** [comment]
Look again, the latest recipe is Linux 5.17.1 -> https://github.com/gobolinux/Recipes/tree/master/Linux/5.17.1
