### ISSUE TITLE
New install, cannot compile recipe CA-Certificates

### ISSUE THREAD

**Issue by leledumbo** [gobolinux/Recipes#201]
Fresh install of 017, because I want to try again after several years. Reading [the wiki](https://wiki.gobolinux.org/Overview/Installing-Gobolinux/GoboLinux-017-Known-Issues-and-Fixes/), some basic houskeeping needed, especially for `Compile` script to break due to SSL certificate is kinda showstopper for most people.

I shouldn't rant too much, so here we go (screenshot because it's installed on a QEMU/KVM instance through virt-manager):
![image](https://github.com/gobolinux/Recipes/assets/270400/fd2ca71d-05ec-4399-9952-ec907e503fc5)
should explain everything already. Anything I can do other than specifying `--no-check-certificate` on every call to `Compile`?

**Comment by leledumbo** [comment]
Answering myself, everything in the article must be executed in order, case closed.

**Comment by Nuc1eoN** [comment]
Great job on figuring it out yourself 👍
Yeah I agree, a new hotfix iso alà 017.1 release is planned.. but no eta yet.

I habe never spun a new release for GoboLinux yet, so it is a bit challenging to say.

Have fun checking out GoboLinux. We are also in dear need to updated docs (content wise). So not everything there might line uo with reality, or lots has just not been written down.

On the other hand, GoboLinux is quite self-explanatory, if one gives it the time. Most things can (or have) be debugged or figured out yourself. But one must keep that in mind ;)
