### ISSUE TITLE
QT environment? 5.7.1 versus 5.9.0 (file: Environment)

### ISSUE THREAD

**Issue by shevegen** [gobolinux/Recipes#21]
Not sure if this is the proper way to report? Anyway:

At this URL:

http://recipes.gobolinux.org/r/?list=Qt&ver=5.9.0-r2&file=Resources/Environment

If you look at the Environment file, it has this content:

export QT_PLUGIN_PATH=/Programs/Qt/5.7.1/plugins:/usr/lib/kde4/plugins${QT_PLUGIN_PATH:+:"$QT_PLUGIN_PATH"}

I found the path strange because it reads Qt/5.7.1 but the program
version of the recipe says 5.9.0.

Thought I'd mention this - feel free to close this at any moment in
time!

**Comment by lucasvr** [comment]
That was indeed a bug. It's been fixed now - thanks for the report!
