### ISSUE TITLE
XZ-Utils versus XZ

### ISSUE THREAD

**Issue by shevegen** [gobolinux/Recipes#23]
I noticed a slight deviation in the XZ-Utils package; is the name correct for the input URL "http://tukaani.org/xz/xz-5.2.3.tar.xz"? The NamingConvention script returns the name XZ :D

**Comment by hishamhm** [comment]
I don't know if it's the case, but sometimes during a project's history they change the name of the tarball (like, `foo-utils` to `fooutils` to just `foo`, or from `libfoo2.15.tar.gz` and `foo-3.2.tar.bz2` etc)... so what we've been doing is that we keep using the old name to give the recipe a linear version history (unless the project itself changes names entirely, from Foo to Bar).

Sometimes we fail to do that and end up with two recipes for the same project in the repo... in those cases it would be best to clean it up, but at times by the time we notice they're already referenced in dependencies, so it's not always easy.

**Comment by lucasvr** [comment]
The author calls the project "XZ Utils", and most mainstream distros name it "xz-utils" too. Let's keep it named as is.
