### ISSUE TITLE
Compile glib fails

### ISSUE THREAD

**Issue by garare992** [gobolinux/Recipes#239]
root@NewMachine master /Data/Compile/Recipes]Compile GDK-Pixbuf
Already up to date.
Compile: Checking dependencies...

CheckDependencies: GLib is installed, but version 2.63.5 does not match given dependency.
CheckDependencies: Compile recipe for GLib 2.75.4 or skip this dependency? [C]Compile/[S]Skip/[CA]Compile All/[SA]Skip Allca
Already up to date.
Compile: Compiling GLib version 2.75.4.
--2024-08-13 18:36:35--  https://gitlab.gnome.org/GNOME/glib/-/archive/2.75.4/glib-2.75.4.tar.bz2
Resolving gitlab.gnome.org (gitlab.gnome.org)... 151.101.193.91, 151.101.1.91, 151.101.65.91, ...
Connecting to gitlab.gnome.org (gitlab.gnome.org)|151.101.193.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: 'glib-2.75.4.tar.bz2'

glib-2.75.4.tar.bz2                 [                     <=>                              ]   6.20M   991KB/s    in 5.8s    

2024-08-13 18:36:42 (1.08 MB/s) - 'glib-2.75.4.tar.bz2' saved [6502073]

Compile: Unpacking file /Data/Compile/Archives/glib-2.75.4.tar.bz2...
The Meson build system
Version: 0.53.1
Source dir: /Data/Compile/Sources/glib-2.75.4
Build dir: /Data/Compile/Sources/glib-2.75.4/_build
Build type: native build

meson.build:1:0: ERROR: Meson version is 0.53.1 but project requires >= 0.60.0

A full log can be found at /Data/Compile/Sources/glib-2.75.4/_build/meson-logs/meson-log.txt
Compile: GLib 2.75.4 - Build failed.

**Comment by Nuc1eoN** [comment]
You have to update Meson via `Alien --install Meson`
