### ISSUE TITLE
Newer Ruby Version - ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

### ISSUE THREAD

**Issue by shevegen** [gobolinux/Recipes#24]
I have noticed, via a "Compile Ruby", that the ruby version on GoboLinux is pretty old.

https://recipes.gobolinux.org/r/?name=ruby&search=Recipes

Or this URL:

http://recipes.gobolinux.org/r/?list=Ruby&file=Recipe

"Ruby 1.9.2_p290-r1"

The current ruby is 2.4.2 and ruby 2.5.0 dev is already in the works, with a new release
being coming at xmas. One good thing is that rubygems is nicely integrated into ruby
by now, and bundler will soon also be officially merged in. So that new ruby version
should definitely be more useful.

The old recipe is at:

https://recipes.gobolinux.org/r/?list=Ruby&ver=1.9.2_p290-r1

The current ruby is at:

ftp://ftp.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.xz

I'll try to create a new recipe for ruby, if nobody else does it, but first I
am setting up the laptop with GoboLinux step by step right now. :)

**Comment by lucasvr** [comment]
Hi Robert! Thanks a lot for looking into this. I have asked before for help on this recipe on #gobolinux, but nobody volunteered.

Besides the obvious version bump, please check that "gem install" stores files under /System/Aliens/RubyGems. The current version is saving modules under /Programs/Ruby/Current, which makes it hard for us to track installed gems.

**Comment by hishamhm** [comment]
I uploaded a new Ruby recipe, including /System/Aliens support.

**Comment by lucasvr** [comment]
I didn't notice that a new recipe was now available. Thanks heaps!
