### ISSUE TITLE
getaddrifo() thread failed to start

### ISSUE THREAD

**Issue by theokeist** [gobolinux/Recipes#242]
For both Compile and UpdateRecipes script when updating fresh new install 

Cloning into '/Data/Compile/Recipes'...
fatal: unable to access 'https://github.com/gobolinux/Recipes.git/': getaddrifo() thread failed to start

fatal: not a git repository (or any of the parent directories): .git
Compile: Could not find a recipe for neofetch^C
martin@NewMachine ~]cd /Data/Compile/Recipes

**Comment by Nuc1eoN** [comment]
Have you followed the [GoboLinux 017 Known Issues and Fixes](https://wiki.gobolinux.org/Overview/Installing-Gobolinux/GoboLinux-017-Known-Issues-and-Fixes/index.html) for fresh installs?

**Comment by Nuc1eoN** [comment]
Closing due to lack of response.
