### ISSUE TITLE
gdk-pixbuf

### ISSUE THREAD

**Issue by ghost** [gobolinux/Recipes#25]
the latest gdk-pixbuf seems to depend on shared mime info

perhaps it can be added to the recipe, if this is true?

I got this compile error with the omst recent gdk-pixbuf:

configure: error: Package requirements (shared-mime-info) were not met:

No package 'shared-mime-info' found

**Comment by hishamhm** [comment]
Sure, an updated recipe is welcome!

**Comment by Nuc1eoN** [comment]
The latest GDK-Pixbuf recipe builds fine for me and Shared-Mime-Info is present in the Dependencies file.

Commit: 8ac547b55cc59f302b7085975f646fa266fbb13f
