### ISSUE TITLE
"3rd party recipes" and as-of-yet not approved recipes (community testing of recipes to ease the workload for the GoboLinux developers)

### ISSUE THREAD

**Issue by ghost** [gobolinux/Recipes#28]
Hello GoboLinux devs,

Please do feel free to close this "issue" request, or perhaps more
of a feature request, at any moment in time.

I try to be succinct.

KDE has quite a lot of programs if you look at the 4 URLs here:

  https://download.kde.org/stable/applications/17.08.2/src/
  https://download.kde.org/stable/frameworks/5.39/
  https://www.kde.org/info/plasma-5.11.2.php
  https://download.kde.org/stable/frameworks/5.39/portingAids/

I counted, via scripts, a total of 344 KDE programs listed there. Not all
of them are ultimately important. For example, KDE Applications has 224
entries. Some of them are ... quite useless, IMO, such as kfloppy:

  ( https://download.kde.org/stable/applications/17.08.2/src/kfloppy-17.08.2.tar.xz )

Anyone still using floppy discs in 2017 and needing a QT-GUI for that? :)

I am tracking almost 244 of the whole KDE programs so far, so still
about 100 missing, in my cookbooks gem.

Adding these programs to the list of manually approved KDE GoboLinux recipes
is a bit much work, I think, for anyone doing so. Even more so when new
updates are about to happen.

Do you think it may be possible to radically simplify the handling of
GoboLinux recipes in general?

An idea I have is to also have and use **"third party recipes"**.

The community could perhaps test any such recipe and then provide feedback
in an automated manner for such recipes.

For example, perhaps we could have code setup like this:

"22 GoboLinux users tested the recipe foobar so far. Of these, 22 reported
no issue or problems."

Then a threshold value could be added, e. g. if 10 different people tested
a recipe, and no problems were reported, it could be automatically approved
or made available, via Compile. Additionally, Compile could get an option
where people can try out as-of-yet unapproved recipes. That would allow
them to use these recipes - and it could also provide feedback to whoever
is doing a review process. The review process often lags in behind, so
this makes this a bit tedious for more casual users of GoboLinux, who may
lack some domain-specific knowledge. (Reason being that they may lack
some knowledge; e. g. how cmake works. KDE uses a lot of cmake-specific
modules, which tend to be installed under /usr/lib/cmake/ by default - no
idea whether GoboLinux is easily able to deal with such recipes, but think
of any semi-casual user who may try to get this to work).

The threshold value is arbitrary - it can be higher or lower. The important
part is that a recipe could be tested more easily by different people and
approved. It does not have to be automatically approved, either, mind you,
but my primary idea here is to allow people to test out recipes more easily
and use them. I assume that many recipes do not need any modification, so
waiting for these before they are approved, is a tedious process and adds,
in my opinion, an unnecessary workload to everyone. 

This may require a few changes to the scripts, such as Compile, e. g.
adding a way to also test "third party recipes" (community recipes)
and to query which recipes may need testing, too. And which unapproved
recipes are available - aka "use at your own risk" recipe. I am not sure
if Compile allows for this but the wiki for Compile does not mention any
such option as of yet:

  https://github.com/gobolinux/Documentation/wiki/Compile

The idea here is to offload some of the workload for the main GoboLinux
developers.

If you want to distinguish between manually reviewed variants from tested
ones by the GoboLinux users (the GoboLinux community), perhaps an icon or
text in different colour could be added to http://recipes.gobolinux.org/r/.

I would also like to recommend that, at http://recipes.gobolinux.org/r/, a
link could be added near the top, towards the currently unapproved 
recipes.

The manual review process is ok, but it depends a lot on time availability,
and for really many programs, such as the mate-stack or the extended
xfce-stack or the kde-stack or the gnome-stack, it's a bit cumbersome.

Some recipes require modification, I understand this. My idea for
these cases would be to have some kind of pre-prepared "modifications"
that users could easily apply onto different recipes, rather than
hardcode specific logic into shell scripts (and into the GoboLinux
recipe at hand). The problem with shell code is that users are required
to understand it, but I also understand that for the time being,
changing this may be a bit too cumbersome.

Anyway, I don't want to make this mail too long so I will finish now.

Main idea: make it possible to use "third party" or GoboLinux-community
approve/tested recipes. I understand that this may require some more 
changes in general, but it can be a long-term goal, say, in the next
6-12 months or so perhaps.

**Comment by eskhool** [comment]
This is a good idea. Maybe take it up on the users mailing list
