### ISSUE TITLE
Please update to uriparser 0.8.6

### ISSUE THREAD

**Issue by hartwork** [gobolinux/Recipes#30]
Hi!

uriparser 0.8.5 has been released:
https://github.com/uriparser/uriparser/releases

Thanks for updating!

**Comment by hartwork** [comment]
Any news or any obstacles I should know about? Thanks!

**Comment by hartwork** [comment]
Any news or any obstacles I should know about? Thanks!

**Comment by hartwork** [comment]
Any news or any obstacles I should know about? Thanks!

**Comment by hartwork** [comment]
0.8.6 has been released now.

**Comment by lucasvr** [comment]
Done.

**Comment by hartwork** [comment]
Thank you!
