### ISSUE TITLE
Please update vulnerable uriparser 0.8.6 to >=0.9.3

### ISSUE THREAD

**Issue by hartwork** [gobolinux/Recipes#37]
Hi!

Just a quick heads up that [uriparser 0.9.1](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.1) with security fixes has been released.

Thanks for updating!

**Comment by hartwork** [comment]
Any news?

**Comment by hartwork** [comment]
Any news?

**Comment by hartwork** [comment]
Any news?

**Comment by hartwork** [comment]
Updated for 0.9.1 now

**Comment by luzpaz** [comment]
@hishamhm care to weigh in on this ?

**Comment by hartwork** [comment]
Ping :smiley:

**Comment by hartwork** [comment]
ping!

**Comment by Nuc1eoN** [comment]
Closed in ca4beb0cf0921fc7022c52acba6460f7579d5496

**Comment by hartwork** [comment]
Thank you! :pray:
