### ISSUE TITLE
Please update GitPython to 2.1.11

### ISSUE THREAD

**Issue by luzpaz** [gobolinux/Recipes#38]
https://github.com/gobolinux/Recipes/tree/master/trunk/GitPython/git
https://github.com/gitpython-developers/GitPython/releases/tag/2.1.11

**Comment by sage-etcher** [comment]
GitPython is a python module, and should be installed by Gobo's `Alien` script, not by Recipe.

To install the most recent version, try this:
``` bash
sudo Alien --install PIP3:GitPython
```

**Comment by Nuc1eoN** [comment]
Yep, that is the correct answer!

In 03ee0762b7eeac73305f964d9b1e2a5dbda38ec4 I have removed the depreciated `GitPython` recipe to prevent confusion. Closing.
