### ISSUE TITLE
Recipes at Gobolinux website are not updated

### ISSUE THREAD

**Issue by 9-** [gobolinux/Recipes#40]
Few months ago I opened the page (http://recipes.gobolinux.org/r/) and I thought the project was dead as the recipes in it hadn't  had any updates for more than 365 days. Fortunately, I just stumbled upon this github to know that the project is still alive.
Please fix the web so that it won't hinder newcomers to try Gobolinux!

**Comment by eskhool** [comment]
I can volunteer to help setup the connection from github to the recipe store

**Comment by lucasvr** [comment]
We're going to look into this issue very soon. Thanks for the heads up.

**Comment by hishamhm** [comment]
The old site was retired: https://recipes.gobolinux.org now points to this Github repo.
