### ISSUE TITLE
[For the next .iso release] Could GCC be compiled with (addition of) --enable-languages=fortran?

### ISSUE THREAD

**Issue by rubyFeedback** [gobolinux/Recipes#44]
Heya lucas, hisham etc...

Would it be possible to add "fortran" to GCC 9.2.0 by default?

I ask this specifically because when trying to compile R (the programming language often used for statistics) it requires fortran.

This is not hugely important because ultimately people can just compile a new gcc, but I thought it would be nice if the default GCC on the next GoboLinux .iso release would support that out of the box.

I am currently testing the new alpha release a bit; will take me some days to give some feedback (I think from the core tools only grep was a bit old and could need update, but the rest seems very recent; glibc could be 2.31 but I guess it is not that important either). Anyway this was really mostly just about GCC, good to see GoboLinux playing Phoenix from the ashes!

**Comment by lucasvr** [comment]
Let me look into this in the coming days. I will either update the recipe as you suggest or push an updated gcc-fortran package.

**Comment by lucasvr** [comment]
017's GCC package is going to include gfortran. I'm going to push an updated ISO this week so you can test it.
