### ISSUE TITLE
Could update to gtk+ 2.24.31 for the Recipes

### ISSUE THREAD

**Issue by shevegen** [gobolinux/Recipes#6]
URL can be found at:

    http://ftp.gnome.org/pub/GNOME/sources/gtk+/2.24/gtk+-2.24.31.tar.xz

I'd try to upload myself but currently only my laptop runs gobolinux without
internet connection. :)

Am first dry-running extensively before installing on my main computer.

**Comment by hishamhm** [comment]
I just updated the recipe in the store, thanks!

http://recipes.gobolinux.org/r/?list=GTK%2B&ver=2.24.31-r1&file=Recipe
