### ISSUE TITLE
github repo truncates recipe list

### ISSUE THREAD

**Issue by Israel-D** [gobolinux/Recipes#9]
Could you make a README.md that has a list of the recipes that exist...
Something simple like this to generate it would work
```bash
#!/bin/bash
README="$PWD/README.md"
INTRO="List of current recipies\n" #If you want to put an intro here you can
echo -e "${INTRO}">"${README}"
for i in **
do
  [[ -d "${i}" ]] && echo " * ${i} " >> "${README}"
done 
## You could also add a footer here to the README if you like
```

**Comment by lucasvr** [comment]
The list of recipes can be retrieved from http://gobolinux.org/recipe-store/MANIFEST in a textual format. That file is updated on a daily basis.
